<a href="https://colab.research.google.com/github/IsadoraPrevitalle/Selecao_de_atributos/blob/main/Sele%C3%A7%C3%A3o_de_Atributos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
base_census = pd.read_csv('census.csv')
base_census.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [ ]:
colunas = base_census.columns
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='object')

In [ ]:
X_census = base_census.iloc[:, 0:14].values
Y_census = base_census.iloc[:, 14].values

In [ ]:
Y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

Pré-Processamento

In [ ]:
from sklearn.preprocessing import LabelEncoder

#Lista de colunas e seus LAbelEncoders
columns = [1,3,5,6,7,8,9,13]
enconders = {col: LabelEncoder() for col in columns}

for col in columns:
    X_census[:, col] = enconders[col].fit_transform(X_census[:, col])

In [ ]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler_census = MinMaxScaler()
X_census_scaler = scaler_census.fit_transform(X_census)
X_census_scaler

array([[0.30136986, 0.875     , 0.0443019 , ..., 0.        , 0.39795918,
        0.95121951],
       [0.45205479, 0.75      , 0.0482376 , ..., 0.        , 0.12244898,
        0.95121951],
       [0.28767123, 0.5       , 0.13811345, ..., 0.        , 0.39795918,
        0.95121951],
       ...,
       [0.56164384, 0.5       , 0.09482688, ..., 0.        , 0.39795918,
        0.95121951],
       [0.06849315, 0.5       , 0.12849934, ..., 0.        , 0.19387755,
        0.95121951],
       [0.47945205, 0.625     , 0.18720338, ..., 0.        , 0.39795918,
        0.95121951]])

Low Variance

In [ ]:
import numpy as np
np.sqrt(X_census[:,0].var()), X_census[:,0].var()

(13.640223092304081, 186.0556860078255)

In [ ]:
for i in range(X_census.shape[1]):
    print(X_census_scaler[:,i].var())

0.034913808595952486
0.03312115190663569
0.005138537590667898
0.06657103564450892
0.029416385024073417
0.06301761677301636
0.09123816653931152
0.10326534394406342
0.04502805169292987
0.22136950173699113
0.00545419549240862
0.008557270623428908
0.015874043397822807
0.03641266114220053


In [ ]:
from sklearn.feature_selection import VarianceThreshold
selecao = VarianceThreshold(threshold=0.05)
X_census_variance = selecao.fit_transform(X_census_scaler)
X_census_variance.shape

(32561, 5)

In [ ]:
X_census_variance

array([[0.6       , 0.66666667, 0.07142857, 0.2       , 1.        ],
       [0.6       , 0.33333333, 0.28571429, 0.        , 1.        ],
       [0.73333333, 0.        , 0.42857143, 0.2       , 1.        ],
       ...,
       [0.73333333, 1.        , 0.07142857, 0.8       , 0.        ],
       [0.73333333, 0.66666667, 0.07142857, 0.6       , 1.        ],
       [0.73333333, 0.33333333, 0.28571429, 1.        , 0.        ]])

In [ ]:
indices = np.where(selecao.variances_ > 0.05)[0]
indices

array([3, 5, 6, 7, 9])

In [ ]:
colunas[indices]

Index(['education', 'marital-status', 'occupation', 'relationship', 'sex'], dtype='object')

In [ ]:
columns = ['education', 'marital-status', 'occupation', 'relationship', 'sex']
df_variance = base_census[columns]
print(df_variance)

         education       marital-status          occupation    relationship  \
0        Bachelors        Never-married        Adm-clerical   Not-in-family   
1        Bachelors   Married-civ-spouse     Exec-managerial         Husband   
2          HS-grad             Divorced   Handlers-cleaners   Not-in-family   
3             11th   Married-civ-spouse   Handlers-cleaners         Husband   
4        Bachelors   Married-civ-spouse      Prof-specialty            Wife   
...            ...                  ...                 ...             ...   
32556   Assoc-acdm   Married-civ-spouse        Tech-support            Wife   
32557      HS-grad   Married-civ-spouse   Machine-op-inspct         Husband   
32558      HS-grad              Widowed        Adm-clerical       Unmarried   
32559      HS-grad        Never-married        Adm-clerical       Own-child   
32560      HS-grad   Married-civ-spouse     Exec-managerial            Wife   

           sex  
0         Male  
1         Male  


In [ ]:
X_LV_final = X_census_scaler[:, indices]
X_LV_final

array([[0.6       , 0.66666667, 0.07142857, 0.2       , 1.        ],
       [0.6       , 0.33333333, 0.28571429, 0.        , 1.        ],
       [0.73333333, 0.        , 0.42857143, 0.2       , 1.        ],
       ...,
       [0.73333333, 1.        , 0.07142857, 0.8       , 0.        ],
       [0.73333333, 0.66666667, 0.07142857, 0.6       , 1.        ],
       [0.73333333, 0.33333333, 0.28571429, 1.        , 0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_census_treinamento, X_census_teste, Y_census_treinamento, Y_census_teste = train_test_split(X_LV_final, Y_census, test_size=0.15, random_state=0)
X_census_treinamento.shape, X_census_teste.shape

((27676, 5), (4885, 5))

In [ ]:
import time
from sklearn.ensemble import RandomForestClassifier

start_ipython= time.time()
random_forest = RandomForestClassifier(criterion='entropy', min_samples_split= 5, n_estimators=100)
random_forest.fit(X_census_treinamento, Y_census_treinamento)
print(f'Tempo de treinamento: {time.time() - start_ipython} segundos')

Tempo de treinamento: 2.000833511352539 segundos


In [ ]:
from sklearn.metrics import accuracy_score, classification_report
previsoes = random_forest.predict(X_census_teste)
accuracy_score(Y_census_teste.astype(str), previsoes.astype(str))

0.8151484135107472

Extra Tree Classifier

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
selecao = ExtraTreesClassifier()
selecao.fit(X_census_scaler.astype(str), Y_census.astype(str))

ExtraTreesClassifier()

In [ ]:
importancias = selecao.feature_importances_
importancias

array([0.15457915, 0.04535953, 0.16318804, 0.03752807, 0.08686812,
       0.07139848, 0.07596928, 0.09567659, 0.01437192, 0.02534409,
       0.0907602 , 0.02897751, 0.09230489, 0.01767415])

In [ ]:
importancias.sum()

1.0

In [ ]:
indices = []
for i in range(len(importancias)):
    if importancias[i] > 0.07:
        indices.append(i)

indices

[0, 2, 4, 5, 6, 7, 10, 12]

In [ ]:
colunas[indices]

Index(['age', 'final-weight', 'education-num', 'marital-status', 'occupation',
       'relationship', 'capital-gain', 'hour-per-week'],
      dtype='object')

In [ ]:
columns = ['age', 'final-weight', 'education-num', 'marital-status', 'occupation','relationship', 'capital-gain', 'hour-per-week']
df_tree = base_census[columns]
print(df_tree)

       age  final-weight  education-num       marital-status  \
0       39         77516             13        Never-married   
1       50         83311             13   Married-civ-spouse   
2       38        215646              9             Divorced   
3       53        234721              7   Married-civ-spouse   
4       28        338409             13   Married-civ-spouse   
...    ...           ...            ...                  ...   
32556   27        257302             12   Married-civ-spouse   
32557   40        154374              9   Married-civ-spouse   
32558   58        151910              9              Widowed   
32559   22        201490              9        Never-married   
32560   52        287927              9   Married-civ-spouse   

               occupation    relationship  capital-gain  hour-per-week  
0            Adm-clerical   Not-in-family          2174             40  
1         Exec-managerial         Husband             0             13  
2       Hand

In [ ]:
X_ETC_final = X_census_scaler[:, indices]
X_ETC_final

array([[0.30136986, 0.0443019 , 0.8       , ..., 0.2       , 0.02174022,
        0.39795918],
       [0.45205479, 0.0482376 , 0.8       , ..., 0.        , 0.        ,
        0.12244898],
       [0.28767123, 0.13811345, 0.53333333, ..., 0.2       , 0.        ,
        0.39795918],
       ...,
       [0.56164384, 0.09482688, 0.53333333, ..., 0.8       , 0.        ,
        0.39795918],
       [0.06849315, 0.12849934, 0.53333333, ..., 0.6       , 0.        ,
        0.19387755],
       [0.47945205, 0.18720338, 0.53333333, ..., 1.        , 0.1502415 ,
        0.39795918]])

In [ ]:
X_census_treinamento, X_census_teste, Y_census_treinamento, Y_census_teste = train_test_split(X_ETC_final, Y_census, test_size=0.15, random_state=0)

In [ ]:
X_census_treinamento.shape, X_census_teste.shape

((27676, 8), (4885, 8))

In [ ]:
start_time = time.time()
random_forest = RandomForestClassifier(criterion='entropy', min_samples_split= 5, n_estimators=100)
random_forest.fit(X_census_treinamento, Y_census_treinamento)
print(f'Tempo de treinamento: {time.time() - start_time} segundos')

Tempo de treinamento: 3.721954822540283 segundos


In [ ]:
previsoes	= random_forest.predict(X_census_teste)
accuracy_score(Y_census_teste.astype(str), previsoes.astype(str))

0.8436028659160696

Todos os atributos

In [ ]:
X_census_treinamento, X_census_teste, Y_census_treinamento, Y_census_teste = train_test_split(X_census, Y_census, test_size=0.15, random_state=0)
X_census_treinamento.shape, X_census_teste.shape

((27676, 14), (4885, 14))

In [ ]:
start_time = time.time()
random_forest = RandomForestClassifier(criterion='entropy', min_samples_split= 5, n_estimators=100)
random_forest.fit(X_census_treinamento, Y_census_treinamento)
print(f'Tempo de treinamento: {time.time() - start_time} segundos')

Tempo de treinamento: 4.297551155090332 segundos


In [ ]:
previsoes = random_forest.predict(X_census_teste)
accuracy_score(Y_census_teste.astype(str), previsoes.astype(str))

0.854042988741044

Redução de dimensionalidade

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [ ]:
base_census = pd.read_csv('census.csv')
base_census.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [121]:
print(df_variance)

      education marital-status occupation relationship      sex
0             9              4          1            1     Male
1             9              2          4            0     Male
2            11              0          6            1     Male
3             1              2          6            0     Male
4             9              2         10            5   Female
...         ...            ...        ...          ...      ...
32556         7              2         13            5   Female
32557        11              2          7            0     Male
32558        11              6          1            4   Female
32559        11              4          1            3     Male
32560        11              2          4            5   Female

[32561 rows x 5 columns]


In [122]:
X_census = df_tree.iloc[:, 0:4].values
Y_census = df_tree.iloc[:, 4].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [123]:
#'education', 'marital-status', 'occupation', 'relationship', 'sex'
#X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,0] = label_encoder_education.fit_transform(X_census[:,0])
X_census[:,1] = label_encoder_marital.fit_transform(X_census[:,1])
X_census[:,2] = label_encoder_occupation.fit_transform(X_census[:,2])
X_census[:,3] = label_encoder_relationship.fit_transform(X_census[:,3])
#X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
#X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [124]:
X_census[0]

array([22, 2671, 12, 4], dtype=object)

In [125]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
X_census = scaler_census.fit_transform(X_census)
X_census

array([[ 0.0307785 , -1.29410611,  1.13473876,  0.92163395],
       [ 0.83750854, -1.25194955,  1.13473876, -0.4062122 ],
       [-0.04256059,  0.59302012, -0.42005962, -1.73405835],
       ...,
       [ 1.4242213 , -0.43245899, -0.42005962,  2.24948009],
       [-1.21598611,  0.39380969, -0.42005962,  0.92163395],
       [ 0.98418673,  1.21115109, -0.42005962, -0.4062122 ]])

In [126]:
from sklearn.preprocessing import StandardScaler
scaler_census = StandardScaler()
X_census = scaler_census.fit_transform(X_census)
X_census

array([[ 0.0307785 , -1.29410611,  1.13473876,  0.92163395],
       [ 0.83750854, -1.25194955,  1.13473876, -0.4062122 ],
       [-0.04256059,  0.59302012, -0.42005962, -1.73405835],
       ...,
       [ 1.4242213 , -0.43245899, -0.42005962,  2.24948009],
       [-1.21598611,  0.39380969, -0.42005962,  0.92163395],
       [ 0.98418673,  1.21115109, -0.42005962, -0.4062122 ]])

In [128]:
from sklearn.model_selection import train_test_split
X_census_treinamento, X_census_teste, Y_census_treinamento, Y_census_teste = train_test_split(X_census, Y_census, test_size=0.15, random_state=0)

In [129]:
X_census_treinamento.shape, X_census_teste.shape

((27676, 4), (4885, 4))

In [130]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_census_treinamento_pca = pca.fit_transform(X_census_treinamento)
X_census_teste_pca = pca.transform(X_census_teste)

In [131]:
X_census_treinamento_pca.shape, X_census_teste_pca.shape

((27676, 2), (4885, 2))

In [132]:
X_census_treinamento

array([[-0.92262973,  1.63337802, -0.42005962, -0.4062122 ],
       [-0.84929064,  0.52606558, -0.03136003, -0.4062122 ],
       [ 1.4242213 ,  1.7821659 ,  1.13473876, -0.4062122 ],
       ...,
       [-1.14264701, -1.52158624, -0.03136003,  1.58555702],
       [ 0.47081307,  0.594508  ,  2.30083755, -0.4062122 ],
       [-0.99596883,  0.12731407, -0.03136003,  0.92163395]])

In [133]:
pca.explained_variance_ratio_

array([0.32753602, 0.25000307])

In [134]:
pca.explained_variance_ratio_.sum()

0.577539089950752

In [135]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest.fit(X_census_treinamento_pca, Y_census_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [136]:
random_forest_census_pca = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest_census_pca.fit(X_census_treinamento_pca, Y_census_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [137]:
previsoes = random_forest_census_pca.predict(X_census_teste_pca)
previsoes

array([' Sales', ' Sales', ' Prof-specialty', ..., ' Exec-managerial',
       ' Exec-managerial', ' Exec-managerial'], dtype=object)

In [138]:
Y_census_teste

array([' Adm-clerical', ' Prof-specialty', ' Sales', ..., ' Sales',
       ' Exec-managerial', ' Exec-managerial'], dtype=object)

In [139]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_census_teste.astype(str), previsoes.astype(str))

0.13961105424769704

Kernel PCA

In [140]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components=2, kernel='rbf')

In [141]:
X_census_treinamento_kpca = kpca.fit_transform(X_census_treinamento)
X_census_teste_kpca = kpca.transform(X_census_teste)

In [142]:
X_census_treinamento_kpca.shape, X_census_teste_kpca.shape

((27676, 2), (4885, 2))

In [143]:
X_census_treinamento_kpca

array([[ 0.23577106,  0.50514909],
       [ 0.18273546,  0.2442782 ],
       [-0.17414408,  0.36547633],
       ...,
       [ 0.30540543, -0.48108208],
       [-0.18530548,  0.17568798],
       [ 0.62268358, -0.12532983]])

In [144]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=40, criterion='entropy', random_state=0)
random_forest.fit(X_census_treinamento_kpca, Y_census_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=0)

In [145]:
previsoes = random_forest.predict(X_census_teste_kpca)
previsoes

array([' Transport-moving', ' Other-service', ' Exec-managerial', ...,
       ' Sales', ' Adm-clerical', ' Exec-managerial'], dtype=object)

In [146]:
Y_census_teste

array([' Adm-clerical', ' Prof-specialty', ' Sales', ..., ' Sales',
       ' Exec-managerial', ' Exec-managerial'], dtype=object)

In [147]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_census_teste.astype(str), previsoes.astype(str))

0.1435005117707267